language: php
dist: trusty
sudo: required
cache:
  directories:
    - vendor/
php:
  - 7.0
services:
  - mongodb
  - docker
addons:
  apt:
    packages:
    - nginx
    - uuid-runtime
  hosts:
    - localhost
    - gandalf.dev
env:
  global:
    - DOCKER_HUB_ACCOUNT=nebo15
    - MAIN_BRANCHES="master develop staging"
    - RELEASE_BRANCH="master"
    - TZ=Europe/Kiev
    - secure: "Qvv4W3LxRt+LHxSWlttfpYUNW5Upf/6kxQbDf3Kz3Z8M90RJq4Ltr0HjMQnQHB87KOtJ9Db37WRt4ioX6M6jpfMqEbNmUK0tdmV5Vu8/oDy9Hp++I8fA6hjHz6N3VLgLUMEmLPpQ7PNN3eIe1k5AzIN/gPsyDFq0U0P7uHd5ln9EyRkN1kj9bxrw2S5XvDOUSkrisfnkb8bH1l5M8oqsCL7N1MFJ9vyIi6YWJtIwG1ChTrscAyl2xV7UQ32kvbEQ3UUb09ovZ+SWOjTHLN3yo35nWer4XVstbJfZXV+RcHV0BZ3Fj87tXx9++eVaj9dNwKaLcZH8hhLR4Rnoyb626ps1FPdx3c1l9bvGZOOqQXA0iwofRV3CTMS/fsnDe2cYFi8bmlc4dY/eGGg0K4R3qUrOs4D1wLG0+u/hRAmx3ggz8qJz3ELx3B1HB7k8+zRYrSsUcQueWDoJ6y3sNIgmelSApwPBJzf7qrKuD2pR9GUckXF7vtMBs7Ip4+Je4lbhT4ln3zjOuUgOt4sX+xrF9P83TM+dBC84R2HprrqL3KhkuINb2GM68g+w9Dh4XhPcRMMhdS4+8/Fjw40s+Ic/ZSYidKRL7XNV4yLskYCBCK8jHKkPpGonfzKDgvn0PIbeipag8kfJpRApwMs/bB1n+Zx/2p65820xzQbHeKP87k4="
    - secure: "kmdnbrYJGUwkpNPq7K+JkB4FX3GJh7dg3k8n+wckH2DQ5Nu1pvNYbHmaeuUBmK0i/OZHcFa/5hvQij1PzuB8SyFRuiWfyunzCtuWrlJ1RZPZbI9BwXTbeVUUz+FcEeLvmkuc37vpneKjiZuZmwIDAUBsShnT+H8eutekmStI05qPthwePX2j3x5jv4cPugjMDsuoxrZmGDeUkwFZ3v+SfkWhE/RlKxJEmIa6AS4QHyIfJuSE+iWSpxnoDy6tkXkwzhse/wzt7a8Xxg7IY8zBZEWklb5I1ugZTAjffmHzPx9Y1oeys/tBdzNJsqlpc4JrB/MYXkcb/N47RLkNRfwnPpSUaj3Qy4I5a/s08xaD9RkO9eN5EQUjnFpm/6YVGMOanaVLOi/kP8QhJwGKuYuWPxrr+/2ohyxMl8Ognavrnxn280MeNr/fcSfSwMrSePFxBB4v8J58LqU/1Mn6XzLCnlDw8XFLzP71m9o7LXYUCcxEQDPN42c/uacFL2TilWX4p2P+0WqmDkvzP0ELNw08PoaMUOEAucUWEyFeycVEgdFd7qu3ONlohiucVP9LaNhuJmHNotyCOjQj+EKvZZex9dnNQVG7u8laJsY370vrYEa6faEaWlrPB1u7bxVGvjOXqRs3idIKZMzHof3Easj/MHTwBfZrfs0vIhUPJaohk3w="
before_script:
  # Our Nginx config uses /www/gandalf.api path. Preserve it on CI
  - sudo mkdir -p /www
  - sudo ln -s $PWD /www/gandalf.api
  - sudo adduser www-data travis
  # Install and configure nginx
  - ./.travis/scripts/install_nginx.sh
  # Install and configure PHP
  - ./.travis/scripts/install_php.sh
  # Disable XDebug
  - phpenv config-rm xdebug.ini
  # Configure file paths and application environment
  - touch storage/logs/lumen.log
  - sudo chmod 777 -Rf storage/ public/dump/
  - cp ./.env.example ./.env
  # Install dependencies
  - composer install --prefer-source
  # Start PHP-FPM
  - sudo ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # Restart nginx
  - sudo service nginx restart
script:
  # Increment version
  - ./bin/version-increment.sh
  # Run tests
  - vendor/bin/codecept run
  - vendor/bin/phpcs ./app --standard=PSR2 --warning-severity=0
  # Run Docker container
  - sudo ./bin/build.sh
  - sudo ./bin/start.sh
  - sleep 5
  - docker ps
  - RUNNING_CONTAINERS=`docker ps | wc -l`;
  - if [ "${RUNNING_CONTAINERS//[[:space:]]/}" == "1" ]; then echo "[E] Container is not started!" && false; fi;
  # Send request to the container
  - curl http://gandalf-docker.dev:8080/ -v
  - docker logs gandalf.api --details --since 5h
after_failure:
  - ls -l /etc/nginx
  - ls -l /etc/nginx/sites-enabled
  - echo $PWD
  - ls -l ./
  - ls -l ../
  - ls -l /www
  - cat /etc/nginx/sites-enabled/*
  - cat /etc/nginx/nginx.conf
  - cat /var/log/www/*.log;
  - cat /var/log/php-fpm.log;
  - cat $PWD/storage/logs/lumen.log;
  - cat $PWD/tests/_output/*
  - docker logs gandalf.api --details --since 5h
after_success:
  # Submit Docker container to Docker Hub and create GitHub Release by pushing tag with a changelog
 - ./bin/ci/push.sh
